Homework 2
================
Jiaxuan Su

``` r
library(tidyverse)
```

## Problem 1

``` r
subway =
  read_csv(
    "./data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
    col_types = cols(
      Route8 = col_character(),
      Route9 = col_character(),
      Route10 = col_character(),
      Route11 = col_character()
    )
  ) |>
  janitor::clean_names() |>
  select(line:route11, entry, vending, entrance_type, ada) |>
  mutate(entry = entry == "YES")
```

The data include station names, lines, coordinates, routes, entry,
vending, entrance type, and ADA status. I cleaned the names, kept the
needed columns, read routes as character, and changed entry to logical.
There are 1868 rows and 19 columns. The data are not tidy because routes
are in separate columns.

``` r
# distinct stations
subway |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 465

``` r
# ADA compliant stations
subway |>
  filter(ada) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 84

``` r
# proportion allowing entry without vending
subway |>
  filter(vending == "NO") |>
  pull(entry) |>
  mean()
```

    ## [1] 0.3770492

``` r
subway_long =
  subway |>
  pivot_longer(
    route1:route11,
    names_to = "route_number",
    names_prefix = "route",
    values_to = "route_name"
  ) |>
  mutate(route_number = as.numeric(route_number)) |>
  drop_na(route_name)

# stations serving A train
subway_long |>
  filter(route_name == "A") |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 60

``` r
# ADA compliant stations serving A train
subway_long |>
  filter(route_name == "A", ada) |>
  distinct(line, station_name) |>
  nrow()
```

    ## [1] 17

## Problem 2

``` r
trash_file = "./data/202610 Trash Wheel Collection Data.xlsx"

mr_trash =
  readxl::read_excel(
    trash_file, sheet = "Mr. Trash Wheel", range = "A2:N743"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    year = as.numeric(year),
    sports_balls = as.integer(round(sports_balls)),
    wheel = "Mr. Trash Wheel"
  )

professor =
  readxl::read_excel(
    trash_file, sheet = "Professor Trash Wheel",
    range = "A2:M140", na = c("", "dive")
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(wheel = "Professor Trash Wheel")

gwynnda =
  readxl::read_excel(
    trash_file, sheet = "Gwynnda the Good Wheel of the W",
    range = "A2:L395"
  ) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(wheel = "Gwynnda")

trash = bind_rows(mr_trash, professor, gwynnda)

professor_weight = sum(professor$weight_tons, na.rm = TRUE)

gwynnda_butts =
  gwynnda |>
  filter(month == "June", year == 2022) |>
  pull(cigarette_butts) |>
  sum(na.rm = TRUE)

nrow(trash)
```

    ## [1] 1269

``` r
professor_weight
```

    ## [1] 294.96

``` r
gwynnda_butts
```

    ## [1] 18120

For problem 2, I combined the three wheels into 1269 observations. Each
row is one dumpster collection, with variables such as wheel, date,
weight, and cigarette butts. Professor Trash Wheel collected 294.96 tons
of trash. Gwynnda collected 18120 cigarette butts in June 2022.

## Problem 3

``` r
baseline_raw =
  read_csv("./data/MCI_baseline.csv", skip = 1, na = ".") |>
  janitor::clean_names()

baseline =
  baseline_raw |>
  filter(is.na(age_at_onset) | age_at_onset > current_age) |>
  mutate(
    sex = case_match(sex, 0 ~ "Female", 1 ~ "Male"),
    apoe4 = case_match(apoe4, 0 ~ "Non-carrier", 1 ~ "Carrier")
  )
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `sex = case_match(sex, 0 ~ "Female", 1 ~ "Male")`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

``` r
women = filter(baseline, sex == "Female")
```

I skipped the notes row, treated dots as missing, and labeled sex and
APOE4. After excluding baseline MCI cases, I kept 479 of 483 recruits.
Of these, 93 developed MCI. Mean baseline age was 65.03 years, and 30%
of women carried APOE4.

``` r
amyloid =
  read_csv("./data/mci_amyloid.csv", skip = 1) |>
  janitor::clean_names() |>
  rename(id = study_id, time_0 = baseline) |>
  pivot_longer(
    time_0:time_8,
    names_to = "time",
    names_prefix = "time_",
    values_to = "amyloid_ratio"
  ) |>
  mutate(time = as.numeric(time))
```

I skipped the notes row and put each visit in a separate row. The data
have 487 people and 2435 rows, with ID, visit time, and amyloid ratio.
Visits cover 0–8 years, and missing ratios are kept.

``` r
baseline_only = filter(baseline, !(id %in% amyloid$id))

amyloid_only =
  amyloid |>
  filter(!(id %in% baseline$id)) |>
  distinct(id)

mci = inner_join(baseline, amyloid, by = "id")

write_csv(mci, "./data/mci_combined.csv")
```

I found 8 people only in the cleaned baseline data and 16 only in
amyloid. I joined matching IDs, giving 471 people, 2355 rows, and 8
columns. Each row combines demographics and biomarker data for one
visit.
